# Generated by Django 3.1.7 on 2021-04-06 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import logistic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('Address_1', models.CharField(max_length=256)),
                ('Address_2', models.CharField(max_length=256)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Link', models.CharField(blank=True, max_length=500)),
                ('Quantity', models.IntegerField(default=10)),
                ('Order_Date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('ID', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Packs', models.CharField(max_length=60)),
                ('Description', models.TextField(default='Description', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('Shipment_Number', models.CharField(default=logistic.models.ran, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('Shipping_Date', models.DateTimeField(auto_now_add=True)),
                ('Arrive_Date', models.DateTimeField(blank=True, null=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Pickup_Location', models.CharField(choices=[('R', 'Riyadhs office'), ('W', 'West offices'), ('E', 'East Offices'), ('D', 'Home Delivery')], default='of', max_length=50)),
                ('Status', models.CharField(choices=[('Just Registered.', 'Just Registered.'), ('Ready to delievry', 'Ready to delievry'), ('On its way to the customer', 'On its way to the customer'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default=logistic.models.status, max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Bracnh',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.office')),
            ],
        ),
    ]
