# Generated by Django 3.1.7 on 2021-04-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_package_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistic.package'),
        ),
    ]
