# Generated by Django 3.1.7 on 2021-04-08 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_orders_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='ID',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.office')),
            ],
        ),
    ]
