# Generated by Django 3.1.7 on 2021-04-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0008_tracking_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='Warehouse',
        ),
        migrations.AddField(
            model_name='orders',
            name='Warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistic.warehouse'),
            preserve_default=False,
        ),
    ]
