# Generated by Django 3.1.7 on 2021-04-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0009_auto_20210408_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='City',
            field=models.CharField(default='Riyadh', max_length=50),
            preserve_default=False,
        ),
    ]
