# Generated by Django 3.1.7 on 2021-04-09 16:52

from django.db import migrations, models
import django.db.models.deletion
import logistic.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0011_auto_20210408_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='Package',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='logistic.package'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracking',
            name='Status',
            field=models.CharField(choices=[('JR.', 'Just Registered.'), ('RTD', 'Ready to delievry'), ('WH', 'At Warehouse'), ('OTW', 'On its way to the customer'), ('D', 'Delivered'), ('C', 'Canceled')], default=logistic.models.status, max_length=30),
        ),
    ]
