# Generated by Django 3.1.7 on 2021-04-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0012_auto_20210409_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='Package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.package'),
        ),
    ]
