# Generated by Django 3.1.7 on 2021-04-11 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0013_auto_20210409_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.warehouse'),
        ),
    ]
