# Generated by Django 3.1.7 on 2021-04-11 06:23

from django.db import migrations, models
import logistic.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0014_auto_20210411_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='Status',
            field=models.CharField(choices=[('Just Registered.', 'Just Registered.'), ('Ready to delievry', 'Ready to delievry'), ('At Warehouse', 'At Warehouse'), ('On its way to the customer', 'On its way to the customer'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default=logistic.models.status, max_length=30),
        ),
    ]
